Two fixes for RedHat:
- 'property' was renamed to 'prop', so fix the error message
- the 'netmask' as described in the README doesn't work on RedHat:
  NoMethodError: undefined method `length' for 24:Fixnum
  so use the "Debian-style" notation there too.